#!/bin/bash

PROG="${BLOCK_INSTANCE}"

INTERVAL=0.17
MAX_LENGTH=25
ADD_STR=" | "
ADD_LENGTH=${#ADD_STR}

if [[ "${PROG}" != "" ]]; then
  OUT_TEXT=$(eval "${PROG}")
  if [[ $? -ne 0 ]]; then
    sleep 1
    echo "${PROG}"
    echo "${PROG}"
    exit 33
  fi
else
  INFO_PLYCTL=$(playerctl metadata 2>/dev/null)

  if [[ $? -eq 0 ]]; then
    PROG="playerctl"
    INFO_TITLE=$(playerctl metadata title)
    INFO_ALBUM=$(playerctl metadata album)
    INFO_ARTIST=$(playerctl metadata artist)
  else
    PROG="cmus-remote"
    INFO_CMUS=$(cmus-remote -Q 2>/dev/null)
    if [[ $? -eq 0 ]]; then
      INFO_TITLE=$(echo "${INFO_CMUS}" | sed -n -e 's/^.*title//p' | head -n 1)
      INFO_ALBUM=$(echo "${INFO_CMUS}" | sed -n -e 's/^.*album//p' | head -n 1)
      INFO_ARTIST=$(echo "${INFO_CMUS}" | sed -n -e 's/^.*artist//p' | head -n 1)
    else
      sleep 1
      exit
    fi
  fi

  if [[ "${INFO_ARTIST}" ]] && [[ "${INFO_TITLE}" ]]; then
    OUT_TEXT=$(echo "${INFO_ARTIST} - ${INFO_TITLE}" | xargs)
  elif [[ "${INFO_TITLE}" ]]; then
    OUT_TEXT=$(echo "${INFO_TITLE}" | xargs)
  fi
fi

if [[ "${OUT_TEXT}" ]]; then
  CHECK_SUM=$(echo "${PROG}" | md5sum | awk '{print $1}')

  TMP_FILE="/tmp/.scroll-${CHECK_SUM}"

  if [[ -f "${TMP_FILE}" ]]; then
    SCROLL_POS=$(cat "${TMP_FILE}")
  else
    SCROLL_POS=0
  fi

  TEXT_LENGTH=${#OUT_TEXT}
  MAX_OFFSET=$((TEXT_LENGTH +ADD_LENGTH -1))

  if [[ "${TEXT_LENGTH}" -lt "${MAX_LENGTH}" ]]; then
    MAX_LENGTH="${TEXT_LENGTH}"
  fi

  if [[ "${SCROLL_POS}" -gt "${MAX_OFFSET}" ]]; then
    SCROLL_POS=0
  fi

  TEXT_LINE="${OUT_TEXT}${ADD_STR}${OUT_TEXT}${ADD_STR}${OUT_TEXT}"
  TEXT_LINE=${TEXT_LINE:$SCROLL_POS:$MAX_LENGTH}

  echo "<span font_family='monospace'>${TEXT_LINE}</span>"
  echo "<span font_family='monospace'>${TEXT_LINE}</span>"
  echo ""

  SCROLL_POS=$((SCROLL_POS +1))

  echo "${SCROLL_POS}" > "${TMP_FILE}"
  sleep 0.17
else
  sleep 1
fi
