#!/bin/bash

device=${BLOCK_INSTANCE:-/dev/video0}
if [[ -c "${device}" ]]; then
  if [[ "$(fuser /dev/video0)" != "" ]]; then
    echo "rec"
    echo "rec"
    echo ""
  else
    echo "off"
    echo "off"
    echo ""
  fi
fi
